const products = [
    {
      id: 1,
      title: "Apple",
      description: "Fruit",
      price: "250",
      img: "https://images.pexels.com/photos/10000847/pexels-photo-10000847.jpeg?auto=compress&cs=tinysrgb&w=600",
      quantity: 1,
    },
    {
      id: 2,
      title: "Rice",
      description: "Basmati Rice",
      price: "350",
      img: "https://images.pexels.com/photos/4110256/pexels-photo-4110256.jpeg?auto=compress&cs=tinysrgb&w=600",
      quantity: 1,
    },
    {
      id: 3,
      title: "Pineapple",
      description: "Fruit",
      price: "150",
      img: "https://images.pexels.com/photos/189268/pexels-photo-189268.jpeg?auto=compress&cs=tinysrgb&w=600",
      quantity: 1,
    },
    {
      id: 4,
      title: "Cabbage",
      description: "Fruit",
      price: "70",
      img: "https://images.pexels.com/photos/6157051/pexels-photo-6157051.jpeg?auto=compress&cs=tinysrgb&w=600",
      quantity: 1,
    },
    {
      id: 5,
      title: "Spinach",
      description: "Vegitable",
      price: "100",
      img: "https://images.pexels.com/photos/7129126/pexels-photo-7129126.jpeg?auto=compress&cs=tinysrgb&w=600",
      quantity: 1,
    },
    {
      id: 6,
      title: "Cucumber",
      description: "Fruit",
      price: "50",
      img: "https://media.istockphoto.com/id/134448898/photo/picture-of-fresh-cucumber-vegetables-in-supermarket.jpg?s=2048x2048&w=is&k=20&c=kUIKgiYXfi9tO9F9QbGK1JmtSj9nAHzY0xXM2TgtSsk=",
      quantity: 1,
    },
    {
      id: 7,
      title: "Tomato",
      description: "Fruit",
      price: "90",
      img: "https://images.pexels.com/photos/4198043/pexels-photo-4198043.jpeg?auto=compress&cs=tinysrgb&w=600",
      quantity: 1,
    },
    {
      id: 8,
      title: "Potato",
      description: "Fruit",
      price: "85",
      img: "https://images.pexels.com/photos/7129145/pexels-photo-7129145.jpeg?auto=compress&cs=tinysrgb&w=600",
      quantity: 1,
    },
    {
      id: 9,
      title: "Watermelon",
      description: "Fruit",
      price: "200",
      img: "https://images.pexels.com/photos/19390552/pexels-photo-19390552/free-photo-of-close-up-of-green-watermelon.jpeg?auto=compress&cs=tinysrgb&w=600",
      quantity: 1,
    },
  ];
  
  export default products;